# Generated by Django 6.0.3 on 2026-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_alter_roadmap_id_alter_step_id_alter_stepresource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Optional direct link to material for this step'),
        ),
    ]
