# Generated by Django 4.0 on 2026-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='level',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='notes_count',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
