# Generated by Django 6.0.3 on 2026-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dashboard_level_remove_dashboard_notes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
