# Generated by Django 6.0.3 on 2026-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_initial'),
        ('note', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='materials',
            field=models.ManyToManyField(blank=True, to='library.book'),
        ),
    ]
