# Generated by Django 6.0.3 on 2026-04-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('library', '0003_alter_topic_slug'),
        ('note', '0004_alter_note_author'),
        ('roadmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='materials',
        ),
        migrations.AddField(
            model_name='note',
            name='resource_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='note',
            name='resource_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='roadmap.step'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='note_note_created_046d98_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['author', 'is_public'], name='note_note_author__911301_idx'),
        ),
    ]
