# Generated by Django 4.0 on 2026-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_book_id_alter_book_topics_alter_comment_id_and_more'),
        ('note', '0005_remove_note_materials_note_resource_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topics',
            field=models.ManyToManyField(blank=True, to='library.Topic'),
        ),
    ]
