# Generated by Django 4.0 on 2026-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_book_id_alter_book_topics_alter_comment_id_and_more'),
        ('note', '0006_alter_note_id_alter_note_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='materials',
            field=models.ManyToManyField(blank=True, to='library.Book'),
        ),
    ]
