# Generated by Django 6.0.3 on 2026-04-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_directorprofile_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='directorprofile',
            old_name='techers_verified',
            new_name='teachers_verified',
        ),
        migrations.AddField(
            model_name='directorprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='user.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='user.school'),
        ),
    ]
